### ISSUE TITLE
Done in Node Child Process calback

### ISSUE THREAD

**Issue by dtothefp** [mxriverlynn/node-jasmine-async#2]
Hi, I learned about your plugin on your screencasts and have been testing it out.  I'm trying to call done in a callback function for the Node Child Process exit event.  For some reason it doesn't seem to be taking effect and I'm wondering if I'm doing something wrong syntactically? 

https://github.com/dtothefp/grunt-resemble-cli/blob/master/spec/jasmine_node_spec.js

**Comment by mxriverlynn** [comment]
Hi @dtothefp - I cloned your project to my box, ran `npm install` and `grunt jasmine_node`, and it all seemed to work for me. I changed the `exit` event code to include some `console.log` statements, in my copy, and the log statements showed up as expected. The specs ran and passed.

What error are you seeing?

What operating system are you using?

**Comment by dtothefp** [comment]
@derickbailey hey thanks for your reply.  Yeh, I actually messed around with it last night and finally got it working by taking the 'exit' listener into the spec file.  No this morning I pulled down the repo, moved the exit listener back and it works perfectly.  No idea what fixed it overnight, I must have been doing something stupid.  

Thanks for the screencasts and the plugin.

**Comment by mxriverlynn** [comment]
well, at least it's working now :)
